apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: prometheus-pod
  namespace: open-telemetry
  labels:
    app: prometheus-pod
spec:
  selector:
    matchLabels:
      app: prometheus-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-pod
    spec:
      containers:
      - name: prometheus-pod
        image: prom/prometheus
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc
  namespace: open-telemetry
spec:
  selector:
    app:  prometheus-pod
  type: ClusterIP
  ports:
  - name:  tcp
    port:  9090
    targetPort:  9090