apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jaeger-pod
  namespace: open-telemetry
  labels:
    app: jaeger-pod
spec:
  selector:
    matchLabels:
      app: jaeger-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaeger-pod
    spec:
      containers:
      - name: jaeger-pod
        image: jaegertracing/all-in-one:1.57
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 14250
        - containerPort: 14268
        - containerPort: 14269
        - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - port: 16686
      protocol: TCP
      targetPort: http-jaeger
  selector:
    app: jaeger-pod
  sessionAffinity: None
  type: LoadBalancer