apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-master
  namespace: blog
  labels:
    name:  mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  mysql-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  mysql-master
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-master
        resources:
          limits:
            cpu: "1000m"
            memory: "1G"
          requests:
            cpu: "512m"
            memory: "0.5G"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Yaosiqi525
        - name: MYSQL_REPLICATION_USER
          value: yaosiqi
        - name: MYSQL_REPLICATION_PASSWORD
          value: 416759511a      
        ports:
        - containerPort:  3306
          name:  mysql-master
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
        - name: data
          hostPath: 
            path: /data/mysql
      restartPolicy: Always