apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: blog
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /data/mysql
    server: 172.16.152.210